"""Frozen PBPK exposure calibration generated by the v2.3 sweep."""

import hashlib
import json
from typing import Any

from app.core.config import settings

CALIBRATION_VERSION = "PBPK_EXPOSURE_CALIBRATION_V2_3"
CALIBRATION_SOURCE = "INTERNAL_DISTRIBUTIONAL_CALIBRATION"
CATALOG_SNAPSHOT_SHA256 = "0a06e54dbea3dd0c1f9eeb0a11808a14cc9962d7d4f3b2044baa1617f03352d9"
CATALOG_SNAPSHOT_TIMESTAMP_UTC = "2026-08-06T14:42:43+00:00"
PBPK_CONFIG_SHA256 = "685842efd7311615269a9cd66aa9e13fef8f63f1040972b0b456a2c3a92c2eda"
P33_EXPOSURE_INDEX = 8.238769621406693
P66_EXPOSURE_INDEX = 10.919181899644531


def runtime_pbpk_config_snapshot() -> dict[str, Any]:
    """Return the PBPK Phase 1 runtime configuration bound to this calibration."""
    return {
        "allometric": {
            "base_cl_metabolism_70_l_h": settings.PBPK_BASE_CL_METABOLISM_70_L_H,
            "base_cl_renal_70_l_h": settings.PBPK_BASE_CL_RENAL_70_L_H,
            "cardiac_flow_70_l_h": settings.PBPK_CARDIAC_FLOW_70_L_H,
            "plasma_volume_fraction": settings.PBPK_PLASMA_VOLUME_FRACTION,
            "liver_volume_fraction": settings.PBPK_LIVER_VOLUME_FRACTION,
            "kidney_volume_fraction": settings.PBPK_KIDNEY_VOLUME_FRACTION,
        },
        "solver": {
            "duration_hours": 24.0,
            "step_hours": 0.1,
            "method": "RK45",
            "rtol": 1e-6,
            "atol": 1e-8,
            "kp_l": 5.0,
            "kp_k": 2.0,
        },
        "exposure": {
            "formula": "log1p(cmax_liver_mg_l)+log1p(auc_liver_mg_h_l)",
            "p33_quantile": 0.33,
            "p66_quantile": 0.66,
        },
    }


def runtime_pbpk_config_sha256() -> str:
    payload = json.dumps(
        runtime_pbpk_config_snapshot(), sort_keys=True, separators=(",", ":"), allow_nan=False
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def ensure_runtime_config_matches_calibration() -> None:
    if runtime_pbpk_config_sha256() != PBPK_CONFIG_SHA256:
        raise RuntimeError("PBPK runtime configuration berbeda dari calibration v2.3 yang dibekukan.")
